name: movement_disorder
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs
  - aiohttp
  - aiohttp-cors
  - aiosignal
  - annotated-types
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - babel
  - beautifulsoup4
  - bleach
  - bleach-with-css
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - colorful
  - comm
  - contourpy
  - cpython
  - cryptography
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - distlib
  - exceptiongroup
  - executing
  - filelock
  - fonttools
  - fqdn
  - freetype
  - frozenlist
  - fsspec
  - gflags
  - glog
  - gmp
  - gmpy2
  - google-api-core
  - google-auth
  - googleapis-common-protos
  - grpcio
  - h11
  - h2
  - h5py
  - hdf5
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - idna
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - ipywidgets
  - isoduration
  - jedi
  - jinja2
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblzma
  - libnghttp2
  - libopenblas
  - libopentelemetry-cpp
  - libopentelemetry-cpp-headers
  - libparquet
  - libpng
  - libprotobuf
  - libre2-11
  - libsodium
  - libsqlite
  - libssh2
  - libthrift
  - libtiff
  - libtorch
  - libutf8proc
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - lightning-utilities
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multidict
  - munkres
  - nbclient
  - nbconvert-core
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nlohmann_json
  - nomkl
  - notebook
  - notebook-shim
  - numpy
  - opencensus
  - opencensus-context
  - openjpeg
  - openssl
  - optree
  - orc
  - overrides
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - prometheus-cpp
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - propcache
  - proto-plus
  - protobuf
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py-spy
  - pyarrow
  - pyarrow-core
  - pyasn1
  - pyasn1-modules
  - pybind11
  - pybind11-global
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-tzdata
  - python_abi
  - pytorch
  - pytorch-lightning
  - pytz
  - pyu2f
  - pyyaml
  - pyzmq
  - qhull
  - ray-core
  - ray-default
  - ray-tune
  - re2
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - rsa
  - scipy
  - send2trash
  - setproctitle
  - setuptools
  - six
  - sleef
  - smart_open
  - snappy
  - sniffio
  - soupsieve
  - stack_data
  - sympy
  - tabulate
  - tensorboardx
  - terminado
  - tinycss2
  - tk
  - tomli
  - torchmetrics
  - tornado
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - unicodedata2
  - uri-template
  - urllib3
  - virtualenv
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - wrapt
  - xorg-libxau
  - xorg-libxdmcp
  - yaml
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
