name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anaconda-anon-usage
  - archspec
  - boltons
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - conda
  - conda-content-trust
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - distro
  - expat
  - fmt
  - icu
  - idna
  - jsonpatch
  - jsonpointer
  - krb5
  - ld_impl_linux-64
  - libarchive
  - libcurl
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgomp
  - libmamba
  - libmambapy
  - libnghttp2
  - libsolv
  - libssh2
  - libstdcxx-ng
  - libuuid
  - libxml2
  - lz4-c
  - menuinst
  - ncurses
  - openssl
  - packaging
  - pcre2
  - pip
  - platformdirs
  - pluggy
  - pybind11-abi
  - pycosat
  - pycparser
  - pysocks
  - python
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - setuptools
  - sqlite
  - tk
  - tqdm
  - truststore
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml-cpp
  - zlib
  - zstandard
  - zstd
